project: 
  type: website
  output-dir: docs

website:
  title: "Your_Name - Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/username/username.github.io
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Your_Name 2024Â©"
    right: 
      - icon: linkedin
        href: Your_LinkedIn_URL

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "Market Research"
        file: cleansing.qmd
      - text: "Asset Pricing"
        file: exploration.qmd
      - text: "Algorithmic Studies"
        file: story_telling.qmd
      - text: "Systems & Tools"
        file: ml.qmd
      - text: "Full Stack"
        file: full_stack.qmd
      - text: "Competitions"
        file: competition.qmd
  
  # learn more about navication here https://quarto.org/docs/websites/website-navigation.html
  # comment out any of the sections below to turn off the sidebar

  sidebar: 
    - title: "Market Research"
      style: "docked"
      background: light
      contents:
        - text: "Market Research"
          file: cleansing.qmd
        - text: "---"
        - text: "Project 1"
          file: Cleansing_Projects/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Cleansing_Projects/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Cleansing_Projects/project3.qmd
        - text: "---"
    - title: "Asset Pricing"
      style: "docked"
      background: light
      contents:
        - text: "Asset Pricing"
          file: exploration.qmd
        - text: "---"
        - text: "Project 1"
          file: Cleansing_Exploration/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Cleansing_Exploration/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Cleansing_Exploration/project3.qmd
        - text: "---"
    - title: "Algorithmic Studies"
      style: "docked"
      background: light
      contents:
        - text: "Algorithmic Studies"
          file: story_telling.qmd
        - text: "---"
        - text: "Project 1"
          file: Story_Telling/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Story_Telling/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Story_Telling/project3.qmd
        - text: "---"
    - title: "Systems & Tools"
      style: "docked"
      background: light
      contents:
        - text: "Systems & Tools"
          file: ml.qmd
        - text: "---"
        - text: "Project 1"
          file: Machine_Learning/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Machine_Learning/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Machine_Learning/project3.qmd
        - text: "---"
    - title: "Full Stack"
      style: "docked"
      background: light
      contents:
        - text: "Full Stack"
          file: full_stack.qmd
        - text: "---"
        - text: "Project 1"
          file: Full_Stack/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Full_Stack/project2.qmd
        - text: "---"
    - title: "Competition"
      style: "docked"
      background: light
      contents:
        - text: "Competition"
          file: competition.qmd
        - text: "---"
        - text: "Project 1"
          file: Competition/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Competition/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Competition/project3.qmd
        - text: "---"

  
format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



